apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-jncq
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-jncq
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-jncq
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-jncq
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-jncq
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ymfg-tenant/rhtap-demo-app/hacbs-test-project-jncq@sha256:887359a2b7c6f31f9636a9ee569afd55818e0abecebe927c76c6d15f24ee3d99
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
