apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-jncq
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-ymfg-tenant/rhtap-demo-app/hacbs-test-project-jncq@sha256:98fe6f87a7a27a6d05ad9b8c651204e5b53d18b8e944cfe215ab82f9a42d9687
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
